### ISSUE TITLE
Add padding for chat box

### ISSUE THREAD

**Issue by joeyak** [zorchenhimer/MovieNight#11]
During the first run of this server, I had trouble reading the text because the words were so close together. Adding a padding or margin around the words would work. We could do it like twitch does

```css
.chat-line__message, .chat-line__moderation, .chat-line__status {
    padding: .5rem 2rem;
    word-wrap: break-word;
}
```
