### ISSUE TITLE
Video stream stops after playing 5 minutes

### ISSUE THREAD

**Issue by commagray** [zorchenhimer/MovieNight#118]
Hi! Thanks for a nice piece of software.

But, unfortunately, as I described in the title, video in browser stops playing after 5 minutes of stream. After reloading the page, stream continues for the next 5 minutes and stuck again.

I can launch a stream on demand to show the problem.

My configuration contains a Docker container built with Dockerfile from the repo.

```
version: "3"

services:
  live:
    build:
      context: movienight
      dockerfile: Dockerfile
    networks:
      - proxy
    ports:
      - 1935:1935
    volumes:
      - ./config:/config
      - ./emotes:/app/static/emotes
    labels:
      - traefik.enable=true
      - traefik.backend=live
      - traefik.docker.network=proxy
      - traefik.port=8089
      - traefik.frontend.rule=Host:live.mle.party
      - com.centurylinklabs.watchtower.enable=false

networks:
  proxy:
    external: true
```

My web server is Caddy and it pokes Traefik with the following configuration:

```
live.mle.party {
	proxy / http://localhost:8080 {
		transparent
		websocket
	}
	tls
	gzip
}
```

The same result without Trafik, with exposed `8089:8089` port.

Tested:
- streaming via OBS and ffmpeg
- watching the stream via Firefox, Chromium and GNOME Web (aka Epiphany, WebKit-based)

Do I need any extra configuration?

Thanks.
